calculator app
Flutter-Learning-Community/calculator pull request #1
Opened 2022-01-11 03:28 UTC by vignesh235

Basic Calculator App 
![Screenshot from 2022-01-11 08-57-17](https://user-images.githubusercontent.com/95606753/148876360-3144e132-8329-4e15-b99b-e613855defaf.png)
![Screenshot from 2022-01-11 08-57-39](https://user-images.githubusercontent.com/95606753/148876365-8a6b6627-0251-4914-bbb9-654adc68ee6d.png)

2022-01-11 18:04 UTC, KaviyaPeriyasamy requested changes

2022-01-11 18:04 UTC, KaviyaPeriyasamy commented on README.md
> +Here Simple Screenshots
Simple Screenshots means ? @manikandaprabhu123

2022-01-11 18:04 UTC, KaviyaPeriyasamy commented on lib/calc.dart
> +import 'package:flutter/material.dart';
Rename the file to ```calculator_screen.dart``` @vignesh235

2022-01-11 18:04 UTC, KaviyaPeriyasamy commented on lib/calc.dart
> +class clac extends StatefulWidget {
Give valid class name @UnstopableSathish

2022-01-11 18:04 UTC, KaviyaPeriyasamy commented on lib/calc.dart
> +  const clac({ Key? key }) : super(key: key);
Give valid class and state name @UnstopableSathish

2022-01-11 18:04 UTC, KaviyaPeriyasamy commented on lib/calc.dart
> +            customOutlineButton("9"),
Avoid code duplication of customOutlineButton and try to generate dynamically @Nandhinidevi123

2022-01-11 18:04 UTC, KaviyaPeriyasamy commented on lib/calc.dart
> +  // ignore: deprecated_member_use
Need clarification on this commented statement @Barathpalanisamy

2022-01-11 18:04 UTC, KaviyaPeriyasamy commented on README.md
Try to give a detailed explanation of the concepts that are used in this project  @manikandaprabhu123

2022-01-11 18:04 UTC, KaviyaPeriyasamy commented on lib/calc.dart
> +      second = int.parse(text);
Need clarification on ```parse``` @vignesh235

2022-01-11 18:04 UTC, KaviyaPeriyasamy commented on pubspec.lock
>      source: hosted
Explain in detail about pubspec lock file @Barathpalanisamy

2022-01-12 03:05 UTC, manikandaprabhu123 commented on README.md
> +Here Simple Screenshots
Sorry @KaviyaPeriyasamy  it's spelling mistake.. Actually it is sample screenshots

2022-01-12 04:15 UTC, Barathpalanisamy commented on pubspec.lock
>      source: hosted
In pubspec.lock it shows the current version of dependency and other identifying information for every immediate and transitive dependency a package relies on.
The lockfile is generated automatically for you by pub when you run pub get, pub upgrade, or pub downgrade.

2022-01-12 05:03 UTC, UnstopableSathish commented on lib/calc.dart
> +  const clac({ Key? key }) : super(key: key);
Class name and state name changed correctly

2022-01-12 05:04 UTC, UnstopableSathish commented on lib/calc.dart
> +class clac extends StatefulWidget {
Valid class name changed

2022-01-12 05:04 UTC, Barathpalanisamy commented on lib/calc.dart
> +  // ignore: deprecated_member_use
When we use this (// ignore: deprecated_member_use) command the outlineButton shows without the Strikethrough mark.But the command is not used it shows the outlinebutton in Strikethrough format. And the sample images is attached 

![Screenshot from 2022-01-12 10-22-02](https://user-images.githubusercontent.com/95605857/149066224-b1e48932-ed31-445f-b83c-aa6b690ee2b8.png)
![Screenshot from 2022-01-12 10-22-20](https://user-images.githubusercontent.com/95605857/149066230-1c40d4db-6383-40e8-91a8-c0ab419cea7c.png)

2022-01-12 05:21 UTC, manikandaprabhu123 commented on README.md
**README.md  file updated..**

2022-01-24 16:56 UTC, merged